import React from "react";
import { View } from "react-native";

const MockIcon = () => React.createElement(View);
const handler = { get: () => MockIcon };
const proxy = new Proxy({}, handler);

export default proxy;
export const ShoppingBag = proxy;
export const Shield = proxy;
export const Info = proxy;
export const Eye = proxy;
export const EyeOff = proxy;
export const Home = proxy;
export const Link = proxy;
export const Wallet = proxy;
export const User = proxy;
export const Search = proxy;
export const ArrowLeft = proxy;
export const Bell = proxy;
export const Plus = proxy;
export const Clock = proxy;
export const ChevronRight = proxy;
export const Check = proxy;
export const AlertCircle = proxy;
export const Send = proxy;
export const FileText = proxy;
export const Upload = proxy;
export const ChevronDown = proxy;
export const X = proxy;
export const Smartphone = proxy;
export const Copy = proxy;
export const Share = proxy;
export const Camera = proxy;
export const Image = proxy;
export const MapPin = proxy;
export const Package = proxy;
export const Truck = proxy;
export const CheckCircle = proxy;
export const Settings = proxy;
export const LogOut = proxy;
export const HelpCircle = proxy;
export const Star = proxy;
export const Lock = proxy;
export const CreditCard = proxy;
export const Filter = proxy;
export const BarChart2 = proxy;